# Generated by Django 4.1.2 on 2022-11-25 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.CharField(default='¡Bienvenido a Twitter!', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_posteo', models.DateTimeField(default=django.utils.timezone.now)),
                ('contenido', models.TextField()),
                ('usuario_posteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posteos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hora_posteo'],
            },
        ),
    ]
