# Generated by Django 4.1.3 on 2022-11-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwitter', '0003_relaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='202-2026524_person-icon-default-user-icon-png.png', upload_to=''),
        ),
    ]
